<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190126_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.FileField(upload_to=''),
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190126_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.FileField(upload_to=''),
        ),
    ]
>>>>>>> 1dec1ff361299080e76c8789214accf677b3fef6
