# Generated by Django 2.1.5 on 2019-01-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190126_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.FileField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
