# Generated by Django 2.1.5 on 2019-01-26 10:39

from django.db import migrations, models
import music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190126_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(null=True, upload_to='songs/<django.db.models.fields.related.ForeignKey>', validators=[music.validators.validate_song_extension]),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.FileField(blank=True, null=True, upload_to='album_covers/', validators=[music.validators.validate_cover_extension]),
        ),
    ]
