# Generated by Django 2.1.5 on 2019-01-26 10:46

from django.db import migrations, models
import music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190126_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(null=True, upload_to='songs/', validators=[music.validators.validate_song_extension]),
        ),
    ]
