# Generated by Django 2.1.5 on 2019-01-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(null=True, upload_to='album_covers/', validators=[music.validators.validate_cover_extension]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
