# Generated by Django 2.1.5 on 2019-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofileinfo_friends_+', to='accounts.UserProfileInfo'),
        ),
    ]
