# Generated by Django 2.1.5 on 2019-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofileinfo_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofileinfo_friends_+', to='accounts.UserProfileInfo'),
        ),
    ]
